---
- project:
    check:
      jobs:
        - python-builder-build-container-image
    gate:
      jobs:
        - python-builder-build-container-image
    post:
      jobs:
        - python-builder-upload-container-image:
            vars:
              upload_container_image_promote: false
